loc:
DIRT: 10
WOOD: 11
DIAMOND: 12
COMPASS: 13
GRASS: 14
fish: 15
acacia_boat: 16
acacia_door: 17
anvil: 18
apple: 19
armor_stand: 20
arrow: 21
baked_potato: 22
banner: 23
barrier: 24
beacon: 25
bed: 26
bedrock: 27
beef: 28
beetroot: 29
beetroot_seeds: 30
beetroot_soup: 31
birch_boat: 32
birch_door: 33
birch_fence: 34
birch_fence_gate: 25
birch_stairs: 26
black_glazed_terracotta: 27
black_shulker_box: 28
blaze_powder: 29
blaze_rod: 30
blue_glazed_terracotta: 31
blue_shulker_box: 32
boat: 33
bone: 34