player:
  timer: 86400000
  list:
  - minecraft:give {p} minecraft:wooden_sword 1 0 {}
  - minecraft:give {p} minecraft:wooden_pickaxe 1 0 {}
  - minecraft:give {p} minecraft:wooden_axe 1 0 {}
  - minecraft:give {p} minecraft:wooden_shovel 1 0 {}
  - minecraft:give {p} minecraft:coal 8 0 {}
  - minecraft:give {p} minecraft:cooked_beef 16 0 {}
  - minecraft:give {p} minecraft:leather_helmet 1 0 {}
  - minecraft:give {p} minecraft:leather_chestplate 1 0 {}
  - minecraft:give {p} minecraft:leather_leggings 1 0 {}
  - minecraft:give {p} minecraft:leather_boots 1 0 {}
  - minecraft:give {p} minecraft:log2 32 0 {}

warrior:
  timer: 86400000
  list:
  - minecraft:give {p} minecraft:iron_sword 1 0 {}
  - minecraft:give {p} minecraft:iron_pickaxe 1 0 {}
  - minecraft:give {p} minecraft:iron_axe 1 0 {}
  - minecraft:give {p} minecraft:iron_shovel 1 0 {}
  - minecraft:give {p} minecraft:coal 16 0 {}
  - minecraft:give {p} minecraft:cooked_beef 32 0 {}
  - minecraft:give {p} minecraft:iron_helmet 1 0 {}
  - minecraft:give {p} minecraft:iron_chestplate 1 0 {}
  - minecraft:give {p} minecraft:iron_leggings 1 0 {}
  - minecraft:give {p} minecraft:iron_boots 1 0 {}
  - minecraft:give {p} minecraft:bow 1 0 {}
  - minecraft:give {p} minecraft:arrow 32 0 {}
  - minecraft:give {p} minecraft:log2 32 0 {}

phantom:
  timer: 129600000
  list:
  - minecraft:give {p} minecraft:coal 64 0 {}
  - minecraft:give {p} minecraft:cooked_beef 64 0 {}
  - minecraft:give {p} minecraft:bow 1 0 {}
  - minecraft:give {p} minecraft:arrow 64 0 {}
  - minecraft:give {p} minecraft:iron_sword 1 0 {ench:[{id:16,lvl:1}]}
  - minecraft:give {p} minecraft:iron_pickaxe 1 0 {ench:[{id:32,lvl:1}]}
  - minecraft:give {p} minecraft:iron_axe 1 0 {ench:[{id:32,lvl:1}]}
  - minecraft:give {p} minecraft:iron_shovel 1 0 {ench:[{id:32,lvl:1}]}
  - minecraft:give {p} minecraft:iron_helmet 1 0 {ench:[{id:0,lvl:1}]}
  - minecraft:give {p} minecraft:iron_chestplate 1 0 {ench:[{id:0,lvl:1}]}
  - minecraft:give {p} minecraft:iron_leggings 1 0 {ench:[{id:0,lvl:1}]}
  - minecraft:give {p} minecraft:iron_boots 1 0 {ench:[{id:0,lvl:1}]}
  - minecraft:give {p} minecraft:log2 64 0 {}
  - minecraft:give {p} minecraft:fishing_rod 1 0 {ench:[{id:34,lvl:3}]}

griefer:
  timer: 172800000
  list:
  - minecraft:give {p} minecraft:coal 64 0 {}
  - minecraft:give {p} minecraft:cooked_beef 64 0 {}
  - minecraft:give {p} minecraft:bow 1 0 {ench:[{id:48,lvl:1}]}
  - minecraft:give {p} minecraft:arrow 64 0 {}
  - minecraft:give {p} minecraft:iron_sword 1 0 {ench:[{id:16,lvl:2}]}
  - minecraft:give {p} minecraft:iron_pickaxe 1 0 {ench:[{id:32,lvl:2}]}
  - minecraft:give {p} minecraft:iron_axe 1 0 {ench:[{id:32,lvl:2}]}
  - minecraft:give {p} minecraft:iron_shovel 1 0 {ench:[{id:32,lvl:2}]}
  - minecraft:give {p} minecraft:iron_helmet 1 0 {ench:[{id:0,lvl:2}]}
  - minecraft:give {p} minecraft:iron_chestplate 1 0 {ench:[{id:0,lvl:2}]}
  - minecraft:give {p} minecraft:iron_leggings 1 0 {ench:[{id:0,lvl:2}]}
  - minecraft:give {p} minecraft:iron_boots 1 0 {ench:[{id:0,lvl:2}]}
  - minecraft:give {p} minecraft:log2 32 0 {}
  - minecraft:give {p} minecraft:fishing_rod 1 0 {ench:[{id:34,lvl:3}]}

punisher:
  timer: 345600000
  list:
  - minecraft:give {p} minecraft:iron_helmet 1 0 {ench:[{id:0,lvl:3},{id:34,lvl:2}]}
  - minecraft:give {p} minecraft:iron_chestplate 1 0 {ench:[{id:0,lvl:3},{id:34,lvl:2}]}
  - minecraft:give {p} minecraft:iron_leggings 1 0 {ench:[{id:0,lvl:3},{id:34,lvl:2}]}
  - minecraft:give {p} minecraft:iron_boots 1 0 {ench:[{id:0,lvl:3},{id:34,lvl:2}]}
  - minecraft:give {p} minecraft:iron_sword 1 0 {ench:[{id:16,lvl:3},{id:34,lvl:2}]}
  - minecraft:give {p} minecraft:iron_pickaxe 1 0 {ench:[{id:32,lvl:4},{id:34,lvl:2}]}
  - minecraft:give {p} minecraft:iron_axe 1 0 {ench:[{id:32,lvl:4},{id:34,lvl:2}]}
  - minecraft:give {p} minecraft:iron_shovel 1 0 {ench:[{id:32,lvl:4},{id:34,lvl:2}]}
  - minecraft:give {p} minecraft:bow 1 0 {ench:[{id:48,lvl:2}]}
  - minecraft:give {p} minecraft:arrow 64 0 {}
  - minecraft:give {p} minecraft:cooked_beef 64 0 {}
  - minecraft:give {p} minecraft:apple 16 0 {}
  - minecraft:give {p} minecraft:log 64 0 {}
  - minecraft:give {p} minecraft:log2 64 0 {}
  - minecraft:give {p} minecraft:flint_and_steel 1 0 {}
  - minecraft:give {p} minecraft:minecart 1 0 {}
  - minecraft:give {p} minecraft:obsidian 16 0 {}
  - minecraft:give {p} minecraft:rail 16 0 {}
  - minecraft:give {p} minecraft:lava_bucket 1 0 {}
  - minecraft:give {p} minecraft:fishing_rod 1 0 {ench:[{id:34,lvl:3}]}
  - minecraft:give {p} minecraft:totem_of_undying 1 0 {}

phoenix:
  timer: 345600000
  list:
  - minecraft:give {p} minecraft:diamond_helmet 1 0 {ench:[{id:0,lvl:2},{id:34,lvl:2}]}
  - minecraft:give {p} minecraft:diamond_chestplate 1 0 {ench:[{id:0,lvl:2},{id:34,lvl:2}]}
  - minecraft:give {p} minecraft:diamond_leggings 1 0 {ench:[{id:0,lvl:2},{id:34,lvl:2}]}
  - minecraft:give {p} minecraft:diamond_boots 1 0 {ench:[{id:0,lvl:2},{id:34,lvl:2}]}
  - minecraft:give {p} minecraft:diamond_sword 1 0 {ench:[{id:16,lvl:2},{id:19,lvl:1},{id:34,lvl:2}]}
  - minecraft:give {p} minecraft:diamond_pickaxe 1 0 {ench:[{id:32,lvl:2},{id:34,lvl:2}]}
  - minecraft:give {p} minecraft:diamond_axe 1 0 {ench:[{id:32,lvl:2},{id:34,lvl:2}]}
  - minecraft:give {p} minecraft:diamond_shovel 1 0 {ench:[{id:32,lvl:2},{id:34,lvl:2}]}
  - minecraft:give {p} minecraft:bow 1 0 {ench:[{id:48,lvl:3},{id:34,lvl:2}]}
  - minecraft:give {p} minecraft:obsidian 64 0 {}
  - minecraft:give {p} minecraft:log 64 0 {}
  - minecraft:give {p} minecraft:log2 64 0 {}
  - minecraft:give {p} minecraft:chorus_fruit 32 0 {}
  - minecraft:give {p} minecraft:rail 32 0 {}
  - minecraft:give {p} minecraft:minecart 1 0 {}
  - minecraft:give {p} minecraft:arrow 64 0 {}
  - minecraft:give {p} minecraft:apple 32 0 {}
  - minecraft:give {p} minecraft:cooked_beef 16 0 {}
  - minecraft:give {p} minecraft:diamond 16 0 {}
  - minecraft:give {p} minecraft:lava_bucket 1 0 {}
  - minecraft:give {p} minecraft:flint_and_steel 1 0 {}
  - minecraft:give {p} minecraft:fishing_rod 1 0 {ench:[{id:34,lvl:3},{id:61,lvl:1}]}
  - minecraft:give {p} minecraft:totem_of_undying 1 0 {}

ultra:
  timer: 432000000
  list:
  - minecraft:give {p} minecraft:diamond_helmet 1 0 {ench:[{id:0,lvl:3},{id:34,lvl:3}]}
  - minecraft:give {p} minecraft:diamond_chestplate 1 0 {ench:[{id:0,lvl:3},{id:34,lvl:3}]}
  - minecraft:give {p} minecraft:diamond_leggings 1 0 {ench:[{id:0,lvl:3},{id:34,lvl:3}]}
  - minecraft:give {p} minecraft:diamond_boots 1 0 {ench:[{id:0,lvl:3},{id:34,lvl:3}]}
  - minecraft:give {p} minecraft:diamond_sword 1 0 {ench:[{id:16,lvl:3},{id:19,lvl:1},{id:34,lvl:3}]}
  - minecraft:give {p} minecraft:diamond_pickaxe 1 0 {ench:[{id:32,lvl:3},{id:34,lvl:3}]}
  - minecraft:give {p} minecraft:diamond_axe 1 0 {ench:[{id:32,lvl:3},{id:34,lvl:3}]}
  - minecraft:give {p} minecraft:diamond_shovel 1 0 {ench:[{id:32,lvl:3},{id:34,lvl:3}]}
  - minecraft:give {p} minecraft:bow 1 0 {ench:[{id:48,lvl:4},{id:34,lvl:2},{id:50,lvl:1}]}
  - minecraft:give {p} minecraft:obsidian 64 0 {}
  - minecraft:give {p} minecraft:diamond 32 0 {}
  - minecraft:give {p} minecraft:ender_pearl 16 0 {}
  - minecraft:give {p} minecraft:golden_apple 8 0 {}
  - minecraft:give {p} minecraft:chorus_fruit 32 0 {}
  - minecraft:give {p} minecraft:arrow 64 0 {}
  - minecraft:give {p} minecraft:log 64 0 {}
  - minecraft:give {p} minecraft:log2 64 0 {}
  - minecraft:give {p} minecraft:rail 32 0 {}
  - minecraft:give {p} minecraft:minecart 1 0 {}
  - minecraft:give {p} minecraft:flint_and_steel 1 0 {}
  - minecraft:give {p} minecraft:fishing_rod 1 0 {ench:[{id:34,lvl:3},{id:61,lvl:2}]}
  - minecraft:give {p} minecraft:totem_of_undying 1 0 {}

dominator:
  timer: 518400000
  list:
  - minecraft:give {p} minecraft:diamond_helmet 1 0 {ench:[{id:0,lvl:4},{id:34,lvl:4}]}
  - minecraft:give {p} minecraft:diamond_chestplate 1 0 {ench:[{id:0,lvl:4},{id:34,lvl:4}]}
  - minecraft:give {p} minecraft:diamond_leggings 1 0 {ench:[{id:0,lvl:4},{id:34,lvl:4}]}
  - minecraft:give {p} minecraft:diamond_boots 1 0 {ench:[{id:0,lvl:4},{id:34,lvl:4}]}
  - minecraft:give {p} minecraft:diamond_sword 1 0 {ench:[{id:16,lvl:4},{id:34,lvl:3},{id:19,lvl:1}]}
  - minecraft:give {p} minecraft:diamond_pickaxe 1 0 {ench:[{id:32,lvl:4},{id:34,lvl:3},{id:62,lvl:3}]}
  - minecraft:give {p} minecraft:diamond_axe 1 0 {ench:[{id:32,lvl:4},{id:34,lvl:3}]}
  - minecraft:give {p} minecraft:diamond_shovel 1 0 {ench:[{id:32,lvl:4},{id:34,lvl:3}]}
  - minecraft:give {p} minecraft:totem_of_undying 1 0 {}
  - minecraft:give {p} minecraft:totem_of_undying 1 0 {}
  - minecraft:give {p} minecraft:bow 1 0 {ench:[{id:48,lvl:5},{id:34,lvl:3},{id:50,lvl:1}]}
  - minecraft:give {p} minecraft:white_shulker_box 1 0 {}
  - minecraft:give {p} minecraft:experience_bottle 64 0 {}
  - minecraft:give {p} minecraft:chorus_fruit 64 0 {}
  - minecraft:give {p} minecraft:ender_pearl 16 0 {}
  - minecraft:give {p} minecraft:golden_apple 16 0 {}
  - minecraft:give {p} minecraft:arrow 64 0 {}
  - minecraft:give {p} minecraft:fishing_rod 1 0 {ench:[{id:34,lvl:3},{id:61,lvl:3}]}

bonus:
  timer: 259200000
  list:
  - minecraft:give {p} minecraft:diamond 64 0 {}
  - minecraft:give {p} minecraft:ender_pearl 16 0 {}
  - minecraft:give {p} minecraft:golden_apple 16 0 {}
  - minecraft:give {p} minecraft:emerald 16 0 {}
  - minecraft:give {p} minecraft:experience_bottle 64 0 {}
  - minecraft:give {p} minecraft:experience_bottle 64 0 {}
  - minecraft:give {p} minecraft:enchanting_table 1 0 {}
  - minecraft:give {p} minecraft:bookshelf 16 0 {}
  - minecraft:give {p} minecraft:totem_of_undying 1 0 {}
  - minecraft:give {p} minecraft:totem_of_undying 1 0 {}







    



