loc: 'spawn # -1 # 51 # -6'
BREAD: 0.15
CARROT_ITEM: 0.10
ROTTEN_FLESH: 0.05
SPIDER_EYE: 0.10
MELON: 0.07
POTATO_ITEM: 0.10
RAW_FISH: 0.09
SUGAR_CANE: 0.09
BONE: 0.07
STRING: 0.09
FEATHER: 0.07
ENDER_PEARL: 0.17
BLAZE_ROD: 0.20
NETHER_STAR: 150
EMERALD: 1.15
COAL: 0.08
IRON_INGOT: 0.16
GOLD_INGOT: 0.18
DIAMOND: 0.25
GLOWSTONE_DUST: 0.07
GLOWSTONE: 0.28
GHAST_TEAR: 3
BLACK_SHULKER_BOX: 50
RED_SHULKER_BOX: 50
GREEN_SHULKER_BOX: 50
BROWN_SHULKER_BOX: 50
BLUE_SHULKER_BOX: 50
CYAN_SHULKER_BOX: 50
SILVER_SHULKER_BOX: 50
GRAY_SHULKER_BOX: 50
PINK_SHULKER_BOX: 50
LIME_SHULKER_BOX: 50
YELLOW_SHULKER_BOX: 50
LIGHT_BLUE_SHULKER_BOX: 50
MAGENTA_SHULKER_BOX: 50
ORANGE_SHULKER_BOX: 50
WHITE_SHULKER_BOX: 50
TNT: 0.10