loc: need
1: WOOD
2: WOOD
3: WOOD
4: WOOD
5: WOOD
6: WOOD
7: WOOD
8: WOOD
9: WOOD
10: WOOD
11: WOOD
12: WOOD
13: WOOD
14: WOOD
15: WOOD
16: WOOD
17: WOOD
18: WOOD
19: WOOD
20: COBBLESTONE
21: COBBLESTONE
22: COBBLESTONE
23: COBBLESTONE
24: COBBLESTONE
25: COBBLESTONE
26: COBBLESTONE
27: COBBLESTONE
28: COBBLESTONE
29: COBBLESTONE
30: COBBLESTONE
31: COBBLESTONE
