settings:
  '1':
    '1': 'warWorld # -104 # 71 # 200'
    '2': 'warWorld # -104 # 71 # 198'
    '3': 'warWorld # -104 # 71 # 196'
    '4': 'warWorld # -104 # 71 # 194'
    '5': 'warWorld # -104 # 71 # 192'
    '6': 'warWorld # -104 # 71 # 190'
    '7': 'warWorld # -104 # 71 # 188'
    '8': 'warWorld # -104 # 71 # 186'
    '9': 'warWorld # -104 # 71 # 184'
    '10': 'warWorld # -104 # 71 # 182'
  '2':
    '1': 'warWorld # -109 # 71 # 182'
    '2': 'warWorld # -109 # 71 # 198'
    '3': 'warWorld # -109 # 71 # 196'
    '4': 'warWorld # -109 # 71 # 194'
    '5': 'warWorld # -109 # 71 # 192'
    '6': 'warWorld # -109 # 71 # 190'
    '7': 'warWorld # -109 # 71 # 188'
    '8': 'warWorld # -109 # 71 # 186'
    '9': 'warWorld # -109 # 71 # 184'
    '10': 'warWorld # -109 # 71 # 182'