settings:
  '1':
    '1': 'warWorld # -10 # 83 # 43'
    '2': 'warWorld # -8 # 76 # 52'
    '3': 'warWorld # -14 # 76 # 52'
    '4': 'warWorld # -19 # 76 # 52'
    '5': 'warWorld # -24 # 76 # 52'
    '6': 'warWorld # -28 # 76 # 52'
    '7': 'warWorld # -32 # 76 # 48'
    '8': 'warWorld # -32 # 69 # 39'
    '9': 'warWorld # -19 # 66 # 48'
    '10': 'warWorld # -10 # 67 # 42'
  '2':
    '1': 'warWorld # -8 # 78 # -51'
    '2': 'warWorld # -11 # 78 # -51'
    '3': 'warWorld # -19 # 78 # -51'
    '4': 'warWorld # -24 # 78 # -51'
    '5': 'warWorld # -24 # 78 # -4'
    '6': 'warWorld # -32 # 78 # -48'
    '7': 'warWorld # -32 # 78 # -53'
    '8': 'warWorld # -30 # 72 # -61'
    '9': 'warWorld # -20 # 66 # -50'
    '10': 'warWorld # 9 # 67 # -53'