name: RedAge_Clans
version: ${project.version}
main: ru.baronessdev.personal.redage.clans.ClansPlugin
depend:
  - RedAge
  - PlaceholderAPI
commands:
  clan:
    aliases: c
  cc:
    usage: /cc [сообщение]
